#!/usr/bin/env bash
# Minimal manual APK build (no Gradle) for the Hermes phone-connector.
# Uses only the Android SDK command-line build-tools + the JDK.
# aapt2 link -> javac (source/target 11) -> d8 --min-api 26 -> zipalign -> apksigner.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SDK="${ANDROID_HOME:-$HOME/Android/Sdk}"
BT="$SDK/build-tools/36.0.0"
PLATFORM_JAR="$SDK/platforms/android-36/android.jar"
OUT="$HERE/build"
KEYSTORE="$HERE/hermes-dev.keystore"
PKG="com.hermes.connector"

rm -rf "$OUT"
mkdir -p "$OUT/obj" "$OUT/dex"

echo "== 0. Generate BuildConfig.java from ../.env =="
ENV_FILE="$HERE/../.env"

extract_env() {
    # $1 = key. Empty string (not an error) if missing or .env doesn't exist.
    # `|| true` matters under set -e -o pipefail: grep exit 1 on zero matches for a
    # legitimately-absent optional key would otherwise abort the whole script here.
    if [ -f "$ENV_FILE" ]; then
        { grep -E "^${1}=" "$ENV_FILE" || true; } | head -1 | cut -d'=' -f2- | tr -d '\r' | sed -E 's/^["'"'"']|["'"'"']$//g'
    fi
}
# Escape backslash then quote — safe for any literal secret/URL/id content.
escape_java() {
    printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

GEMINI_KEY="$(extract_env gemini_key)"
if [ -z "$GEMINI_KEY" ]; then
    echo "WARNING: gemini_key not found in $ENV_FILE — building with an empty API key." >&2
    echo "         GeminiLiveClient.connect() will fail until this is set and rebuilt." >&2
fi

HERMES_WS_URL="$(extract_env hermes_ws_url)"
HERMES_DEVICE_ID="$(extract_env hermes_device_id)"
HERMES_TOKEN="$(extract_env hermes_token)"
MAX_CALL_MS="$(extract_env max_call_ms)"
if ! printf '%s' "$MAX_CALL_MS" | grep -qE '^[0-9]+$'; then
    [ -n "$MAX_CALL_MS" ] && echo "NOTE: max_call_ms='$MAX_CALL_MS' is not a positive integer — using 600000." >&2
    MAX_CALL_MS="600000"
fi
for pair in "hermes_ws_url:$HERMES_WS_URL" "hermes_device_id:$HERMES_DEVICE_ID" "hermes_token:$HERMES_TOKEN"; do
    key="${pair%%:*}"; val="${pair#*:}"
    if [ -z "$val" ]; then
        echo "NOTE: $key not set in $ENV_FILE — the hermes-core link is disabled; inbound calls" >&2
        echo "      run on the baked-in fallback persona (not an error)." >&2
    fi
done

cat > "$HERE/src/com/hermes/connector/BuildConfig.java" <<EOF
package com.hermes.connector;

// GENERATED by build.sh from ../.env — do not edit by hand, do not commit (see .gitignore).
// Regenerate by re-running build.sh after changing .env.
// GEMINI_API_KEY empty -> GeminiLiveClient.connect() fails.
// Any HERMES_* empty    -> hermes-core link disabled, inbound uses DEFAULT_SYSTEM_INSTRUCTION.
final class BuildConfig {
    static final String GEMINI_API_KEY = "$(escape_java "$GEMINI_KEY")";
    static final String HERMES_WS_URL = "$(escape_java "$HERMES_WS_URL")";
    static final String HERMES_DEVICE_ID = "$(escape_java "$HERMES_DEVICE_ID")";
    static final String HERMES_TOKEN = "$(escape_java "$HERMES_TOKEN")";
    static final long MAX_CALL_MS = ${MAX_CALL_MS}L;

    private BuildConfig() {}
}
EOF

echo "== 1. Link manifest -> base.apk (no resources) =="
"$BT/aapt2" link \
    -o "$OUT/base.apk" \
    --manifest "$HERE/AndroidManifest.xml" \
    -I "$PLATFORM_JAR" \
    --min-sdk-version 26 \
    --target-sdk-version 34

echo "== 2. Compile Java =="
javac -source 11 -target 11 \
    -classpath "$PLATFORM_JAR" \
    -d "$OUT/obj" \
    "$HERE"/src/com/hermes/connector/*.java

echo "== 3. Dex =="
"$BT/d8" --min-api 26 --output "$OUT/dex" \
    --lib "$PLATFORM_JAR" \
    $(find "$OUT/obj" -name '*.class')

echo "== 4. Merge classes.dex into APK =="
cp "$OUT/dex/classes.dex" "$OUT/classes.dex"
( cd "$OUT" && zip -j base.apk classes.dex )

echo "== 5. Zipalign =="
"$BT/zipalign" -f -p 4 "$OUT/base.apk" "$OUT/aligned.apk"

echo "== 6. Sign (dev-only self-signed key; priv-app grant comes from the"
echo "      allowlist file + priv-app path, not from this signature) =="
if [ ! -f "$KEYSTORE" ]; then
    keytool -genkeypair -v \
        -keystore "$KEYSTORE" \
        -alias hermes \
        -keyalg RSA -keysize 2048 -validity 10000 \
        -storepass hermes123 -keypass hermes123 \
        -dname "CN=Hermes Connector Dev, OU=dev, O=dev, L=dev, S=dev, C=US"
fi
"$BT/apksigner" sign \
    --ks "$KEYSTORE" --ks-pass pass:hermes123 --key-pass pass:hermes123 \
    --out "$OUT/HermesConnector.apk" \
    "$OUT/aligned.apk"

echo "== Done: $OUT/HermesConnector.apk =="
"$BT/apksigner" verify --print-certs "$OUT/HermesConnector.apk" || true
